---
kind: Service
apiVersion: v1
metadata:
  name: antenna-canary
  labels:
    app: antenna
    role: canary
    service: load-balancer
spec:
  ports:
  - name: http
    port: 80
    targetPort: http
    protocol: TCP
  - name: https
    port: 443
    targetPort: https
    protocol: TCP
  selector:
    app: antenna
    role: canary
    service: reverse-proxy
  type: LoadBalancer
