static-production:
  build: ./docker/node
  command: ./grunt/compile.sh
  environment:
    VIRTUAL_HOST: 'https://cdn.antenna.is'
    ANTENNA_URL: 'http://www.antenna.is'
    ANTENNA_API_URL: 'https://api.antenna.is'
    ANTENNA_STATIC_URL: 'https://cdn.antenna.is'
    EVENTS_URL: 'http://events.antenna.is'
  volumes:
    - .:/code/antenna
web-production:
  command: sleep 1
  build: ./docker/python
  environment:
    DEBUG: 'true'
    DJANGO_LOG_LEVEL: 'DEBUG'
    VIRTUAL_ENV: '/code/antenna/virtualenvs/docker'
    PYTHONPATH: '/code'
    PATH: '/code/antenna/virtualenvs/docker/bin:$PATH'
    PYTHONDONTWRITEBYTECODE: 'true'
    ANTENNA_STATIC_STORAGE: storages.backends.s3boto.S3BotoStorage
  volumes:
    - .:/code/antenna
