# Adapted from https://github.com/GoogleCloudPlatform/kube-jenkins-imager

---
kind: Service
apiVersion: v1
metadata:
  name: antenna
  labels:
    name: antenna
    service: load-balancer
    app: load-balancer
spec:
  ports:
  - name: http
    port: 80
    targetPort: http
    protocol: TCP
  - name: https
    port: 443
    targetPort: https
    protocol: TCP
  selector:
    name: antenna
    service: reverse-proxy
  type: LoadBalancer
