---
apiVersion: extensions/v1beta1
kind: HorizontalPodAutoscaler
metadata:
  name: antenna-static-nginx
spec:
  cpuUtilization:
    targetPercentage: 75
  maxReplicas: 50
  minReplicas: 1
  scaleRef:
    apiVersion: v1
    kind: ReplicationController
    name: antenna-static-nginx
    subresource: scale
