---
apiVersion: extensions/v1beta1
kind: HorizontalPodAutoscaler
metadata:
  name: antenna-http
spec:
  cpuUtilization:
    targetPercentage: 80
  maxReplicas: 50
  minReplicas: 1
  scaleRef:
    apiVersion: v1
    kind: ReplicationController
    name: antenna-http
    subresource: scale
