---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: antenna-celery
spec:
  replicas: 1
  template:
    metadata:
      name: antenna-celery
      labels:
        name: antenna
        service: celery
        app: antenna
    spec:
      containers:
        - name: antenna-celery
          image: gcr.io/antenna-array/antenna:latest
          args: ['./manage.py', 'celeryd', '--loglevel=debug', '--concurrency=1']
          resources:
            requests:
              cpu: "100m"
              memory: "250Mi"
            limits:
              cpu: "1"
              memory: "500Mi"
          env:
            - name: DJANGO_LOG_LEVEL
              value: DEBUG
            - name: VIRTUAL_HOST
              valueFrom:
                secretKeyRef:
                  name: antenna-env-secret
                  key: virtual-host
            - name: ANTENNA_URL
              valueFrom:
                secretKeyRef:
                  name: antenna-env-secret
                  key: antenna-url
            - name: ANTENNA_STATIC_URL
              valueFrom:
                secretKeyRef:
                  name: antenna-env-secret
                  key: antenna-static-url
            - name: ANTENNA_INTERNAL_STATIC_URL
              valueFrom:
                secretKeyRef:
                  name: antenna-env-secret
                  key: antenna-internal-static-url
            - name: EVENTS_URL
              valueFrom:
                secretKeyRef:
                  name: antenna-env-secret
                  key: events-url
            - name: DATABASE_HOST_MASTER
              valueFrom:
                secretKeyRef:
                  name: mysql-ssl-secret
                  key: database-host-master
            - name: DATABASE_SSL_MASTER_CLIENT_KEY
              value: /secrets/master-client-key.pem
            - name: DATABASE_SSL_MASTER_CLIENT_CERT
              value: /secrets/master-client-cert.pem
            - name: DATABASE_SSL_MASTER_SERVER_CA
              value: /secrets/master-server-ca.pem
            - name: DATABASE_HOST_SLAVE1
              valueFrom:
                secretKeyRef:
                  name: mysql-ssl-secret
                  key: database-host-slave1
            - name: DATABASE_SSL_SLAVE1_CLIENT_KEY
              value: /secrets/slave1-client-key.pem
            - name: DATABASE_SSL_SLAVE1_CLIENT_CERT
              value: /secrets/slave1-client-cert.pem
            - name: DATABASE_SSL_SLAVE1_SERVER_CA
              value: /secrets/slave1-server-ca.pem
            - name: DATABASE_HOST_SLAVE2
              valueFrom:
                secretKeyRef:
                  name: mysql-ssl-secret
                  key: database-host-slave2
            - name: DATABASE_SSL_SLAVE2_CLIENT_KEY
              value: /secrets/slave1-client-key.pem
            - name: DATABASE_SSL_SLAVE2_CLIENT_CERT
              value: /secrets/slave1-client-cert.pem
            - name: DATABASE_SSL_SLAVE2_SERVER_CA
              value: /secrets/slave1-server-ca.pem
            - name: MEMCACHED_HOST_DEFAULT
              value: memcached-default
            - name: MEMCACHED_HOST_REDUNDANT
              value: memcached-redundant
            - name: RABBITMQ_HOST
              value: amqp
            - name: BQ_TABLE_PREFIX
              valueFrom:
                secretKeyRef:
                  name: bigquery-secret
                  key: bq-table-prefix
            - name: EMAIL_BACKEND
              valueFrom:
                secretKeyRef:
                  name: email-secret
                  key: email-backend
            - name: MAILGUN_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: email-secret
                  key: mailgun-access-key
            - name: MAILGUN_SERVER_NAME
              valueFrom:
                secretKeyRef:
                  name: email-secret
                  key: mailgun-server-name
            - name: EMAIL_HOST
              valueFrom:
                secretKeyRef:
                  name: email-secret
                  key: email-host
          volumeMounts:
            - name: mysql-ssl-secret
              mountPath: /secrets
              readOnly: true
      volumes:
        - name: antenna-env-secret
          secret:
            secretName: antenna-env-secret
        - name: mysql-ssl-secret
          secret:
            secretName: mysql-ssl-secret
        - name: bigquery-secret
          secret:
            secretName: bigquery-secret
        - name: email-secret
          secret:
            secretName: email-secret
