---
apiVersion: extensions/v1beta1
kind: HorizontalPodAutoscaler
metadata:
  name: antenna-static-http
spec:
  cpuUtilization:
    targetPercentage: 80
  maxReplicas: 50
  minReplicas: 1
  scaleRef:
    kind: Deployment
    apiVersion: extensions/v1beta1
    name: antenna-static-http
    subresource: scale
