# Adapted from https://github.com/GoogleCloudPlatform/kube-jenkins-imager

---
kind: ReplicationController
apiVersion: v1
metadata:
  name: antenna-nginx
spec:
  replicas: 1
  template:
    metadata:
      name: antenna-nginx
      labels:
        name: antenna
        service: reverse-proxy
        app: nginx
    spec:
      containers:
        - name: antenna-nginx
          image: gcr.io/antenna-array/nginx-ssl-proxy
          resources:
            requests:
              cpu: "500m"
              memory: "500Mi"
            limits:
              cpu: "1"
              memory: "1Gi"
          env:
            - name: SERVICE_HOST_ENV_NAME
              value: ANTENNA_HTTP_SERVICE_HOST
            - name: SERVICE_PORT_ENV_NAME
              value: ANTENNA_HTTP_SERVICE_PORT_HTTP
            - name: ENABLE_SSL
              value: 'false'
            - name: ENABLE_BASIC_AUTH
              value: 'false'
          ports:
            - name: http
              containerPort: 80
            - name: https
              containerPort: 443
#          volumeMounts:
#            - name: secrets
#              mountPath: /etc/secrets
#              readOnly: true
#      volumes:
#        - name: secrets
#          secret:
#            secretName: antenna-nginx-secrets
