---
kind: Service
apiVersion: v1
metadata:
  name: dd-agent
  labels:
    app: dd-agent
spec:
  ports:
  - name: dogstatsdport
    port: 8125
    targetPort: dogstatsdport
    protocol: TCP
  selector:
    app: dd-agent
  type: ClusterIP
