var sitesBySilo = {
            "style": [{"label": "HighSnobiety", "url": "https://www.highsnobiety.com", "dfp": "cmn_highsnobiety", "kw": "s_sty", "feature": 1},
                      {"label": "Selectism", "url": "https://www.selectism.com", "dfp": "cmn_selectism", "kw": "s_sty", "feature": 1},
                      {"label": "PorHomme", "url": "https://www.porhomme.com", "dfp": "cmn_porhomme", "kw": "s_sty", "feature": 1},
                      {"label": "FreshnessMag", "url": "https://www.freshnessmag.com", "dfp": "cmn_freshnessmag", "kw": "s_sty", "feature": 1},
                      {"label": "Complex Style", "url": "https://www.complex.com/style", "dfp": "cmn_complex", "kw": "s_sty", "feature": 1},
                      {"label": "BarbershopConnect", "url": "https://www.barbershopconnect.com", "dfp": "cmn_barbershopconnect", "kw": "s_sty", "feature": 0},
                      {"label": "ArrestedMotion", "url": "https://www.arrestedmotion.com", "dfp": "cmn_arrestedmotion", "kw": "s_sty", "feature": 0},
                      {"label": "Highsnobette", "url": "https://www.highsnobette.com", "dfp": "cmn_highsnobette", "kw": "s_sty", "feature": 0},
                      {"label": "Juxtapoz", "url": "https://www.juxtapoz.com", "dfp": "cmn_juxtapoz", "kw": "s_sty", "feature": 0},
                      {"label": "KarmaloopTV", "url": "https://www.karmalooptv.com", "dfp": "cmn_karmalooptv", "kw": "s_sty", "feature": 0},
                      {"label": "Kineda", "url": "https://www.kineda.com", "dfp": "cmn_kineda", "kw": "s_sty", "feature": 0},
                      {"label": "MaestroKnows", "url": "https://www.maestroknows.com", "dfp": "cmn_maestroknows", "kw": "s_sty", "feature": 0},
                      {"label": "MechanicalDummy", "url": "https://www.mechanicaldummy.com", "dfp": "cmn_mechanicaldummy", "kw": "s_sty", "feature": 0},
                      {"label": "RadCollector", "url": "https://www.radcollector.com", "dfp": "cmn_radcollector", "kw": "s_sty", "feature": 0},
                      /**{"label": "RawrDenim", "url": "https://www.rawrdenim.com", "dfp": "cmn_rawrdenim", "kw": "s_sty", "feature": 0},*/
                      {"label": "Slamxhype", "url": "https://www.slamxhype.com", "dfp": "cmn_slamxhype", "kw": "s_sty", "feature": 0},
                      {"label": "StupidDOPE", "url": "https://www.stupiddope.com", "dfp": "cmn_stupiddope", "kw": "s_sty", "feature": 0},
                      {"label": "StyleEngine", "url": "https://www.styleengine.com", "dfp": "cmn_styleengine", "kw": "s_sty", "feature": 0},
                      {"label": "TheChoosyBeggar", "url": "https://www.thechoosybeggar.com", "dfp": "cmn_thechoosybeggar", "kw": "s_sty", "feature": 0},
                      {"label": "UpscaleHype", "url": "https://www.upscalehype.com", "dfp": "cmn_upscalehype", "kw": "s_sty", "feature": 0},
                      {"label": "MassAppeal", "url": "https://www.massappeal.com", "dfp": "cmn_massappeal", "kw": "s_sty", "feature": 0},
                      {"label": "IAmPacked", "url": "https://www.iampacked.com", "dfp": "cmn_iampacked", "kw": "s_sty", "feature": 0},
                      {"label": "FourPins", "url": "https://four-pins.com", "dfp": "fourpins", "kw": "s_sty", "feature": 0},
                      {"label": "RefinedGuy", "url": "https://www.refinedguy.com/", "dfp": "cmn_refinedguy", "kw": "s_sty", "feature": 0},
                      {"label": "12OzProphet", "url": "https://www.12ozprophet.com", "dfp": "cmn_12ozprophet", "kw": "s_sty", "feature": 0},
                      {"label": "ClutterMagazine", "url": "https://www.cluttermagazine.com", "dfp": "cmn_cluttermagazine", "kw": "s_sty", "feature": 0},
                      {"label": "StreetWearDeals", "url": "https://www.streetweardeals.com", "dfp": "cmn_streetweardeals", "kw": "s_sty", "feature": 0},
                      {"label": "InfiniteLegRoom", "url": "https://infinitelegroom.com", "dfp": "cmn_infinitelegroom", "kw": "s_sty", "feature": 0},
                      {"label": "HiConsumption", "url": "https://www.hiconsumption.com", "dfp": "cmn_hiconsumption", "kw": "s_sty", "feature": 0},
                      {"label": "Green-Label", "url": "https://www.green-label.com", "dfp": "cmn_green-label", "kw": "s_sty", "feature": 0},
                      {"label": "DMarge", "url": "https://www.dmarge.com", "dfp": "cmn_dmarge", "kw": "s_sty", "feature": 0},
                      {"label": "AcclaimMag", "url": "https://www.acclaimmag.com", "dfp": "acclaimmag", "kw": "s_sty", "feature": 0},
                      {"label": "NYSkateboarding", "url": "https://www.nyskateboarding.com", "dfp": "nyskateboarding", "kw": "s_sty", "feature": 0},
                      {"label": "InkedMag", "url": "https://www.inkedmag.com", "dfp": "inkedmag", "kw": "s_sty", "feature": 0},
                      {"label": "MisterMort", "url": "https://mistermort.com", "dfp": "mistermort", "kw": "s_sty", "feature": 0},
                      {"label": "TheStatusLife", "url": "https://thestatuslife.com", "dfp": "thestatuslife", "kw": "s_sty", "feature": 0},
                      {"label": "AmongMen", "url": "https://amongmen.com", "dfp": "amongmen", "kw": "s_sty", "feature": 0},
                      {"label": "WhiskeyGrade", "url": "https://whiskeygrade.com", "dfp": "whiskeygrade", "kw": "s_sty", "feature": 0}],

            "sneakers": [/*{"label": "NiceKicks", "url": "https://www.nicekicks.com", "dfp": "cmn_nicekicks", "kw": "s_sne", "feature": 1},*/
                      {"label": "SoleCollector", "url": "https://solecollector.com", "dfp": "cmn_solecollector", "kw": "s_sne", "feature": 1},
                      {"label": "KicksonFire", "url": "https://www.kicksonfire.com", "dfp": "cmn_kicksonfire", "kw": "s_sne", "feature": 1},
                      {"label": "SneakerNews", "url": "https://www.sneakernews.com", "dfp": "cmn_sneakernews", "kw": "s_sne", "feature": 1},
                      {"label": "SneakerFreaker", "url": "https://www.sneakerfreaker.com", "dfp": "cmn_sneakerfreaker", "kw": "s_sne", "feature": 1},
                      {"label": "Complex Sneakers", "url": "https://www.complex.com/sneakers", "dfp": "cmn_complex", "kw": "s_sne", "feature": 1},
                      {"label": "CelebKicks", "url": "https://www.celebkicks.com", "dfp": "cmn_celebkicks", "kw": "s_sne", "feature": 0},
                      {"label": "JordansDaily", "url": "https://www.jordansdaily.com", "dfp": "cmn_jordansdaily", "kw": "s_sne", "feature": 0},
                      {"label": "KicksDeals", "url": "https://www.kicksdeals.com", "dfp": "cmn_kicksdeals", "kw": "s_sne", "feature": 0},
                      {"label": "SneakerWareApp", "url": "https://www.sneakerwareapp.com", "dfp": "cmn_sneakerwareapp", "kw": "s_sne", "feature": 0},
                      {"label": "SneakerWatch", "url": "https://www.sneakerwatch.com", "dfp": "cmn_sneakerwatch", "kw": "s_sne", "feature": 0},
                      {"label": "TheShoeGame", "url": "https://www.theshoegame.com", "dfp": "cmn_theshoegame", "kw": "s_sne", "feature": 0},
                      {"label": "SneakerReport", "url": "https://sneakerreport.com", "dfp": "cmn_sneakerreport", "kw": "s_sne", "feature": 0},
                      {"label": "WearTesters", "url":"https://weartesters.com", "dfp": "weartesters", "kw": "s_sne", "feature": 0},
                      {"label": "PaintOrThread", "url":"https://paintorthread.com", "dfp": "paintorthread", "kw": "s_sne:", "feature": 0},
                      {"label": "KixAndTheCity", "url": "https://kixandthecity.com", "dfp": "kixandthecity", "kw": "s_sne", "feature": 0}],

            "music": [{"label": "HipHopDX", "url": "https://www.hiphopdx.com", "dfp": "cmn_hiphopdx", "kw": "s_mus", "feature": 1},
                      {"label": "DJBooth", "url": "https://www.djbooth.net", "dfp": "cmn_djbooth", "kw": "s_mus", "feature": 1},
                      {"label": "AllMusic", "url":"https://www.allmusic.com", "dfp":"allmusic", "kw":"s_mus", "feature": 1},
                      {"label": "2DopeBoyz", "url": "https://www.2dopeboyz.com", "dfp": "cmn_2dopeboyz", "kw": "s_mus", "feature": 1},
                      {"label": "Complex Music", "url": "https://www.complex.com/music", "dfp": "cmn_complex", "kw": "s_mus", "feature": 1},
                      {"label": "AllHipHop", "url": "https://www.allhiphop.com", "dfp": "cmn_allhiphop", "kw": "s_mus", "feature": 0},
                      {"label": "DoAndroidsDance", "url": "https://doandroidsdance.com", "dfp": "cmn_doandroidsdance", "kw": "s_mus", "feature": 0},
                      {"label": "AudioMack", "url": "https://www.audiomack.com", "dfp": "cmn_audiomack", "kw": "s_mus", "feature": 0},
                      {"label": "BallerStatus", "url": "https://www.ballerstatus.com", "dfp": "cmn_ballerstatus", "kw": "s_mus", "feature": 0},
                      {"label": "BaebleMusic", "url": "https://www.baeblemusic.com", "dfp":"baeblemusic", "kw":"s_mus", "feature": 0},
                      {"label": "BeatsPerMinute", "url": "https://www.beatsperminute.com", "dfp": "cmn_beatsperminute", "kw": "s_mus", "feature": 0},
                      {"label": "BestofBothOffices", "url": "https://www.bestofbothoffices.com", "dfp": "cmn_bestofbothoffices", "kw": "s_mus", "feature": 0},
                      {"label": "BoomShots", "url": "https://www.boomshots.com", "dfp": "cmn_boomshots", "kw": "s_mus", "feature": 0},
                      {"label": "Dajaz1", "url": "https://www.dajaz1.com", "dfp": "cmn_dajaz1", "kw": "s_mus", "feature": 0},
                      {"label": "DatNewCudi", "url": "https://www.datnewcudi.com", "dfp": "cmn_datnewcudi", "kw": "s_mus", "feature": 0},
                      {"label": "Earmilk", "url": "https://www.earmilk.com", "dfp": "cmn_earmilk", "kw": "s_mus", "feature": 0},
                      {"label": "EgoTripLand", "url": "https://www.egotripland.com", "dfp": "cmn_egotripland", "kw": "s_mus", "feature": 0},
                      {"label": "FakeShoreDrive", "url": "https://www.fakeshoredrive.com", "dfp": "cmn_fakeshoredrive", "kw": "s_mus", "feature": 0},
                      {"label": "FreeOnSmash", "url": "https://www.freeonsmash.com", "dfp": "cmn_freeonsmash", "kw": "s_mus", "feature": 0},
                      {"label": "HypeVideos", "url": "https://www.hypevideos.com", "dfp": "cmn_hypevideos", "kw": "s_mus", "feature": 0},
                      {"label": "IllRoots", "url": "https://www.illroots.com", "dfp": "cmn_illroots", "kw": "s_mus", "feature": 0},
                      {"label": "LilWayneHQ", "url": "https://www.lilwaynehq.com", "dfp": "cmn_lilwaynehq", "kw": "s_mus", "feature": 0},
                      {"label": "LiveMixTapes", "url": "https://www.livemixtapes.com", "dfp": "cmn_livemixtapes", "kw": "s_mus", "feature": 0},
                      {"label": "LX-Goods", "url": "https://www.lx-goods.com", "dfp": "cmn_lxgoods", "kw": "s_mus", "feature": 0},
                      {"label": "MissInfoTV", "url": "https://www.missinfo.tv", "dfp": "cmn_missinfo", "kw": "s_mus", "feature": 0},
                      {"label": "NahRight", "url": "https://www.nahright.com", "dfp": "cmn_nahright", "kw": "s_mus", "feature": 0},
                      {"label": "OnlyTheBeat", "url": "https://www.onlythebeat.com", "dfp": "onlythebeat", "kw": "s_mus", "feature": 0},
                      {"label": "PigeonsandPlanes", "url": "https://www.pigeonsandplanes.com", "dfp": "cmn_pigeonsandplanes", "kw": "s_mus", "feature": 0},
                      {"label": "Refined Hype", "url": "https://www.refinedhype.com", "dfp": "cmn_refinedhype", "kw": "s_mus", "feature": 0},
                      {"label": "TheMaskedGorilla", "url": "https://www.themaskedgorilla.com", "dfp": "cmn_themaskedgorilla", "kw": "s_mus", "feature": 0},
                      {"label": "VibeToThis", "url": "https://www.vibetothis.com", "dfp": "cmn_vibetothis", "kw": "s_mus", "feature": 0},
                      {"label": "VladTV", "url": "https://www.vladtv.com", "dfp": "cmn_vladtv", "kw": "s_mus", "feature": 0},
                      {"label": "YouHeardThatNew", "url": "https://www.youheardthatnew.com", "dfp": "cmn_youheardthatnew", "kw": "s_mus", "feature": 0},
                      {"label": "YoungMoneyHQ", "url": "https://www.youngmoneyhq.com", "dfp": "cmn_youngmoneyhq", "kw": "s_mus", "feature": 0},
                      {"label": "MassAppeal", "url": "https://www.massappeal.com", "dfp": "cmn_massappeal", "kw": "s_mus", "feature": 0},
                      /**{"label": "InFlexWeTrust", "url": "https://www.inflexwetrust.com", "dfp": "cmn_inflexweTrust", "kw": "s_mus", "feature": 0},*/
                      {"label": "NME", "url": "https://www.nme.com", "dfp": "cmn_nme", "kw": "s_mus", "feature": 0},
                      {"label": "RareSoul", "url": "https://www.raresoul.com", "dfp": "cmn_raresoul", "kw": "s_mus", "feature": 0},
                      {"label": "RunTheTrap", "url":"https://www.runthetrap.com", "dfp": "cmn_runthetrap", "kw": "s_mus", "feature": 0},
                      {"label": "PrefixMag", "url":"https://www.prefixmag.com", "dfp": "prefixmag", "kw": "s_mus", "feature": 0},
                      {"label": "Elektrocircus", "url":"https://www.elektrocircus.com", "dfp":"elektrocircus", "kw":"s_mus", "feature":0},
                      {"label": "MagneticMag", "url":"https://www.magneticmag.com", "dfp":"magneticmag", "kw":"s_mus", "feature":0},
                      {"label": "ThatDROP", "url":"https://www.thatdrop.com", "dfp":"thatdrop", "kw":"s_mus", "feature":0},
                      {"label": "urb", "url": "https://urb.com", "dfp":"urb", "kw":"s_mus", "feature": 0}],

            "videoGames": [{"label": "GameRanx", "url": "https://www.gameranx.com", "dfp": "cmn_gameranx", "kw": "s_gam", "feature": 1},
                      {"label": "GameRant", "url": "https://www.gamerant.com", "dfp": "cmn_gamerant", "kw": "s_gam", "feature": 1},
                      {"label": "Shoryuken", "url": "https://www.shoryuken.com", "dfp": "cmn_shoryuken", "kw": "s_gam", "feature": 1},
                      {"label": "PastaPadre", "url": "https://www.pastapadre.com", "dfp": "cmn_pastapadre", "kw": "s_gam", "feature": 1},
                      {"label": "Complex Video Games", "url": "https://www.complex.com/video-games", "dfp": "cmn_complex", "kw": "s_gam", "feature": 1},
                      {"label": "PlaystationUniveristy", "url": "https://www.playstationuniveristy.com", "dfp": "cmn_planetplaystationuniversity", "kw": "s_gam", "feature": 0}],

            "popCulture": [{"label": "MoeJackson", "url": "https://www.moejackson.com", "dfp": "cmn_moejackson", "kw": "s_pop", "feature": 1},
                      {"label": "Collider", "url": "https://collider.com", "dfp": "collider", "kw": "s_pop", "feature": 1},
                      {"label": "JoBlo", "url": "https://www.joblo.com", "dfp": "cmn_joblo", "kw": "s_pop", "feature": 1},
                      {"label": "FirstWeFeast", "url": "https://www.firstwefeast.com", "dfp": "cmn_firstwefeast", "kw": "s_pop", "feature": 1},
                      {"label": "Complex Pop Culture", "url": "https://www.complex.com/pop-culture", "dfp": "cmn_complex", "kw": "s_pop", "feature": 1},
                      {"label": "HollywoodHeavy", "url": "https://www.hollywoodheavy.com", "dfp": "cmn_hollywoodheavy", "kw": "s_pop", "feature": 0},
                      {"label": "CelebritySchoolPics", "url": "https://www.celebrityschoolpics.com", "dfp": "cmn_celebrityschoolpics", "kw": "s_pop", "feature": 0},
                      {"label": "AnalogHype", "url": "https://www.analoghype.com", "dfp": "cmn_analoghype", "kw": "s_pop", "feature": 0},
                      {"label": "FreeOnSmash", "url": "https://www.freeonsmash.com", "dfp": "cmn_freeonsmash", "kw": "s_pop", "feature": 0},
                      {"label": "GetTheBigPicture.net", "url": "https://www.getthebigpicture.net", "dfp": "cmn_getthebigpicture", "kw": "s_pop", "feature": 0},
                      {"label": "GeekTyrant.com", "url": "https://www.geektyrant.com", "dfp": "cmn_geektyrant", "kw": "s_pop", "feature": 0},
                      {"label": "VideoGoneViral", "url": "https://www.videogoneviral.com", "dfp": "cmn_videogoneviral", "kw": "s_pop", "feature": 0},
                      {"label": "WorldOfDance", "url": "https://www.worldofdance.com", "dfp": "cmn_worldofdance", "kw": "s_pop", "feature": 0},
                      {"label": "TheFilmStage", "url": "https://thefilmstage.com", "dfp": "cmn_thefilmstage", "kw": "s_pop", "feature": 0},
                      {"label": "Ranker", "url": "https://ranker.com", "dfp": "cmn_ranker", "kw": "s_pop", "feature": 0},
                      {"label": "HipsterRunoff", "url": "https://hipsterrunoff.com", "dfp": "cmn_hipsterrunoff", "kw": "s_pop", "feature": 0},
                      {"label": "ShockMansion", "url": "https://shockmansion.com", "dfp": "cmn_shockmansion", "kw": "s_pop", "feature": 0},
                      {"label": "BehindTheHustle", "url": "https://behindthehustle.com", "dfp": "cmn_behindthehustle", "kw": "s_pop", "feature": 0},
                      {"label": "YouGottaEatThis", "url": "https://yougottaeatthis.com", "dfp": "cmn_yougottaeatthis", "kw": "s_pop", "feature": 0},

                      {"label": "TheLeakTV", "url": "https://www.theleak.tv", "dfp": "theleaktv", "kw": "s_pop", "feature": 0},
                      {"label": "WeGotThisCovered", "url": "https://wegotthiscovered.com", "dfp": "wegotthiscovered", "kw": "s_pop", "feature": 0},
                      {"label": "Latino-Review", "url": "https://www.latino-review.com", "dfp": "latinoreview", "kw": "s_pop", "feature": 0}],

            "sports": [/**{"label": "DimeMag", "url": "https://www.dimemag.com", "dfp": "cmn_dimemag", "kw": "s_spo", "feature": 1},*/
                      {"label": "TotalProSports", "url": "https://www.totalprosports.com", "dfp": "cmn_totalprosports", "kw": "s_spo", "feature": 1},
                      {"label": "RadCollector", "url": "https://www.radcollector.com", "dfp": "cmn_radcollector", "kw": "s_spo", "feature": 1},
                      {"label": "TheHoopDoctors", "url": "https://www.thehoopdoctors.com", "dfp": "cmn_thehoopdoctors", "kw": "s_spo", "feature": 1},
                      {"label": "Complex Sports", "url": "https://www.complex.com/sports", "dfp": "cmn_complex", "kw": "s_spo", "feature": 1},
                      {"label": "BasketballInsiders", "url": "https://basketballinsiders.com", "dfp": "basketballinsiders", "kw": "s_spo", "feature": 1},
                      {"label": "6Magazine", "url": "https://6magazineonline.com/", "dfp": "cmn_6magazineonline", "kw": "s_spo", "feature": 0},
                      {"label": "BallJunkie", "url": "https://balljunkie.com/", "dfp": "cmn_balljunkie", "kw": "s_spo", "feature": 0},
                      {"label": "ASportingClub", "url": "https://asportingclub.com", "dfp": "cmn_asportingclub", "kw": "s_spo", "feature": 0},
                      /**{"label": "HighSchoolHoop", "url": "https://www.highschoolhoop.com", "dfp": "cmn_highschoolhoop", "kw": "s_spo", "feature": 0},*/
                      {"label": "JapaneseSportCars", "url": "https://www.japanesesportcars.com", "dfp": "cmn_japanesesportcars", "kw": "s_spo", "feature": 0},
                      {"label": "SheridanHoops", "url": "https://www.sheridanhoops.com", "dfp": "cmn_sheridanhoops", "kw": "s_spo", "feature": 0},
                      /**{"label": "TheCageDoctors", "url": "https://www.thecagedoctors.com", "dfp": "cmn_thecagedoctors", "kw": "s_spo", "feature": 0},*/
                      /**{"label": "TheDugoutDoctors", "url": "https://www.thedugoutdoctors.com", "dfp": "cmn_thedugoutdoctors", "kw": "s_spo", "feature": 0},*/
                      {"label": "TheOriginalWinger", "url": "https://www.theoriginalwinger.com", "dfp": "cmn_theoriginalwinger", "kw": "s_spo", "feature": 0},
                      /**{"label": "ThePigSkinDoctors", "url": "https://thepigskindoctors.com", "dfp": "cmn_thepigskindoctors", "kw": "s_spo", "feature": 0},*/
                      /**{"label": "ThePuckDoctors", "url": "https://thepuckdoctors.com", "dfp": "cmn_thepuckdoctors", "kw": "s_spo", "feature": 0},*/
                      /**{"label": "HouseofHighlights", "url": "https://houseofhighlights.com", "dfp": "cmn_houseofhighlights", "kw": "s_spo", "feature": 0},*/
                      {"label": "BallerMindFrame", "url": "https://ballermindframe.com", "dfp": "ballermindframe", "kw": "s_spo", "feature": 0},
                      {"label": "TriangleOffense", "url": "https://triangleoffense.com", "dfp": "triangleoffense", "kw": "s_spo", "feature": 0},
                      {"label": "CourtsideAccess", "url": "https://www.courtsideaccess.com", "dfp": "courtsideaccess", "kw": "s_spo", "feature": 0},
                      {"label": "DraftExpress", "url": "https://www.draftexpress.com", "dfp":"draftexpress", "kw":"s_spo", "feature": 0},
                      {"label": "SWOL", "url": "https://swol.co", "dfp":"swol", "kw":"s_spo", "feature": 0}]
        };
