---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: mailcatcher-oauth2-proxy
spec:
  replicas: 1
  template:
    metadata:
      name: mailcatcher-oauth2-proxy
      labels:
        name: mailcatcher-oauth2-proxy
        service: oauth2-proxy
    spec:
      containers:
        - name: oauth2-proxy
          image: a5huynh/oauth2_proxy:latest
          args:
            - --config=/secrets/oauth2-proxy-cfg/oauth2-proxy.cfg
            - --upstream=http://mailcatcher/
          resources:
            limits:
              cpu: "100m"
              memory: "250Mi"
          ports:
            - name: http
              containerPort: 4180
          volumeMounts:
            - name: mailcatcher-oauth2-proxy-cfg
              mountPath: /secrets/oauth2-proxy-cfg
              readOnly: true
      volumes:
        - name: mailcatcher-oauth2-proxy-cfg
          secret:
            secretName: mailcatcher-oauth2-proxy-cfg
