---
kind: Service
apiVersion: v1
metadata:
  name: mailcatcher-oauth2-proxy
spec:
  ports:
  - name: http
    port: 80
    targetPort: http
    protocol: TCP
  selector:
    name: mailcatcher-oauth2-proxy
