---
kind: Service
apiVersion: v1
metadata:
  name: antenna-http
  labels:
    app: antenna
    role: primary
    service: http
spec:
  clusterIP: 10.71.254.178
  ports:
  - name: http
    port: 80
    targetPort: http
    protocol: TCP
  selector:
    app: antenna
    role: primary
    service: http
