---
kind: Service
apiVersion: v1
metadata:
  name: antenna
  labels:
    app: antenna
    role: primary
    service: load-balancer
    letsencrypt: production
  annotations:
    vhosts: api.antenna.is www.antenna.is antenna.is
spec:
  clusterIP: 10.71.242.148
  ports:
  - name: http
    port: 80
    targetPort: http
    protocol: TCP
  - name: https
    port: 443
    targetPort: https
    protocol: TCP
  selector:
    app: antenna
    role: primary
    service: reverse-proxy
  type: LoadBalancer
