FROM {{IMAGE}}:{{VERSION}}

RUN ["/bin/bash", "-c", "' \
    echo Compiling static assets for {{ENVIRONMENT}} && \
    . docker/env/{{ENVIRONMENT}}.env && \
    echo ANTENNA_URL == $ANTENNA_URL && \
    grunt/compile.sh'"]
